services:
  redis:
    image: "redis:alpine"
    expose:
      - 6379
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
  db:
    image: "postgres:latest"
    restart: always
    environment:
      - POSTGRES_USER=duckchess
      - POSTGRES_PASSWORD_FILE=/run/secrets/postgres_password
      - POSTGRES_DB=duckchess
    volumes:
      - db-data:/var/lib/postgresql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    expose:
      - 5432
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "duckchess"]
      interval: 10s
      timeout: 5s
      retries: 5
    secrets:
      - postgres_password
  edge-service:
    build:
      context: .
      dockerfile: edge-service/Dockerfile
    ports:
      - 8000:8000
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    environment:
      POSTGRES_USER: duckchess
      POSTGRES_PASSWORD_FILE: /run/secrets/postgres_password
      POSTGRES_HOST: db
      POSTGRES_PORT: 5432
      REDIS_URL: redis://redis:6379
      SECRET_KEY_FILE: /run/secrets/secret_key
      SERVE_PORT: 8000
      BIND_ADDRESS: 0.0.0.0
      LOG_LEVEL: normal
    secrets:
      - secret_key
      - postgres_password
  game-service:
    build:
      context: .
      dockerfile: game-service/Dockerfile
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    environment:
      REDIS_URL: redis://redis:6379
      AUTOCLAIM_TIME_MS: 3000
      CONSUMER_ID: game-service
      CONSUMER_GROUP: game-workers

volumes:
  db-data:

secrets:
  secret_key:
    environment: SECRET_KEY
  postgres_password:
    environment: POSTGRES_PASSWORD
